#ifndef APP_MEM_H
#define APP_MEM_H


#define PCIE_POTOCOL_MEM_ADDR (0x40000000)
#define PCIE_POTOCOL_MEM_SIZE (1024u)


#define PCIE_IMAGE_MEM_ADDR (PCIE_POTOCOL_MEM_ADDR + PCIE_POTOCOL_MEM_SIZE)
#define PCIE_IMAGE_MEM_SZIE (0x7FF00000 - PCIE_POTOCOL_MEM_SIZE)

#define PCIE_PROTOCOL_CMD_MAX_LEN 128
#define PCIE_PROTOCOL_EXTREA_MAX_LEN 256

#define PCIE_POTOCOL_HOST_CMD_MEM_ADDR PCIE_POTOCOL_MEM_ADDR   //0x400000000
#define PCIE_POTOCOL_HOST_CMD_ACK_MEM_ADDR (PCIE_POTOCOL_MEM_ADDR + PCIE_PROTOCOL_CMD_MAX_LEN)  //256

#define PCIE_POTOCOL_SLV_CMD_MEM_ADDR (PCIE_POTOCOL_HOST_CMD_ACK_MEM_ADDR + PCIE_PROTOCOL_CMD_MAX_LEN) //
#define PCIE_POTOCOL_SLV_CMD_ACK_MEM_ADDR (PCIE_POTOCOL_SLV_CMD_MEM_ADDR + PCIE_PROTOCOL_CMD_MAX_LEN) //512B

#define PCIE_POTOCOL_HOST_EXTRA_MEM_ADDR (PCIE_POTOCOL_SLV_CMD_ACK_MEM_ADDR + 256)
#define PCIE_POTOCOL_SLV_EXTRA_MEM_ADDR  (PCIE_POTOCOL_HOST_EXTRA_MEM_ADDR + 256) //all 1024 bit


#endif
